---
#ansible-playbook -i localhost, -e "instances=['mongodb', 'catalogue', 'redis', 'user', 'cart', 'mysql', 'shipping', 'rabbitmq', 'payment', 'frontend']" 01-roboshop.yaml

# ansible-playbook -i localhost, \ -e '{"instances":["mongodb", "catalogue", "redis", "user", "cart", "shipping", 
# "mysql", "rabbitmq", "payment", "frontend"]}' \ 01-roboshop.yaml
#====================================================================================================================
# PLAY: Create EC2 Instances and Route53 DNS Records
#Purpose: Automates the AWS infrastructure setup for the RoboShop project
#====================================================================================================================
- name: create ec2 instance and route53 records
  hosts: all
  connection: local
  vars:
    sg_id: sg-0a697c68c12d16675
    ami_id: ami-0220d79f3f480ecf5
    domain_name: deekshi88s.online
    env: dev

    #THE TOGGLE SWITCH: Change to "destroy" to delete everything
    action: create

    #THE FULL LIST: ALL 10 microservices to be created
    instances:
    - mongodb
    - catalogue
    
  tasks:
  #===================================================================================================================
  # PHASE 1: CREATE INFRASTRUCTURE (Runs only if action == "create")
  #===================================================================================================================

  # 1. Launch EC2 servers for every item in the 'instances' list
  - name: create ce2 insatnces
    amazon.aws.ec2_instance:
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      name: "{{ item }}-{{ env }}"
      tags:
        Project: "roboshop"
        Component: "{{ item }}-{{ env }}"
        Environment: "{{ env }}"
        Name: "{{item }}-{{ env }}"
    loop: "{{ instances }}" 
    register: ec2_output 
    when: action == "create"

  # 2. Print the AWSresponse (for debugging)
  - name: print the ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}" 
    when: action == "create"   
  
  # 3. Create private DNS records (internal communication)
  - name: create route53 records (private)
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"  
      record: "{{ item.item }}-{{ env }}.{{ domain_name }}" # mongodb-dev.deekshi88s.online, frontend-dev.deekshi88s.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true      # Critical Fix: Updatesrecord if it already exists
    loop: "{{ ec2_output.results }}"
    when: action == "create"    

  # 4. Create Public DNS record (ONLY for FRONTEND to be accessible from internet)
  - name: create route53 records (public)
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"  
      record: "roboshop-{{ env }}.{{ domain_name }}" # roboshop-dev.deekshi88s.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_output.results }}" 
    when: # and
    - item.item == "frontend"
    - action == "create"
  
  #===============================================================================================================================
  # PHASE 2. DESTROY INFRASTRUCTURE (Runs only if action == "destroy")
  #===============================================================================================================================

  # 5. Delete DNS records
  - name: delete route53 records
    amazon.aws.route53:
      zone: "{{ domain_name }}"
      state: absent        
      record: "{{ item }}-{{ env }}.{{ domain_name }}"
      type: A
      ttl: 1
    loop: "{{ instances }}"
    when: action == "destroy" 

  # 6. Terminate EC2 servers    
  - name: delete ec2 instance
    amazon.aws.ec2_instance: 
      name: "{{ item }}-{{ env }}"
      state: absent
      wait: false
    loop: "{{ instances }}"
    when: action == "destroy"
